export const dom = {
    videoUpload: document.getElementById('video-upload'),
    fileNameDisplay: document.getElementById('file-name'),
    videoPreview: document.getElementById('video-preview'),
    processButton: document.getElementById('process-button'),
    generateGifsButton: document.getElementById('generate-gifs-button'),
    gridContainer: document.getElementById('grid-container'),
    settingsRowsInput: document.getElementById('settings-rows'),
    settingsColsInput: document.getElementById('settings-cols'),
    videoRowsInput: document.getElementById('video-rows'),
    videoColsInput: document.getElementById('video-cols'),
    thresholdInput: document.getElementById('threshold'),
    thresholdValue: document.getElementById('threshold-value'),
    paddingTopInput: document.getElementById('padding-top'),
    paddingRightInput: document.getElementById('padding-right'),
    paddingBottomInput: document.getElementById('padding-bottom'),
    paddingLeftInput: document.getElementById('padding-left'),
    gridOverlay: document.getElementById('grid-overlay'),
    gifFpsInput: document.getElementById('gif-fps'),
    gifQualityInput: document.getElementById('gif-quality'),
    gifDitherInput: document.getElementById('gif-dither'),
    gifSpeedInput: document.getElementById('gif-speed'),
    gifDurationInput: document.getElementById('gif-duration'),
    exportOptions: document.getElementById('export-options'),
    selectAllButton: document.getElementById('select-all-button'),
    deselectAllButton: document.getElementById('deselect-all-button'),
    toggleSettingsButton: document.getElementById('toggle-settings-button'),
    settingsPanel: document.getElementById('settings-panel'),
    twitchToggle: document.getElementById('twitch-toggle'),
};

export const state = {
    video: null,
    previewLoopId: null,
    isCapturing: false,
    cellFrames: [],
    gifWorkerBlob: null,
    cellCanvases: [],
    hiddenCanvas: null,
    hiddenCtx: null,
    // A new property to store rendered video dimensions and offset
    renderedVideoRect: { x: 0, y: 0, width: 0, height: 0 },
    // A new array to hold stable capture dimensions for each cell
    cellCaptureRects: [],
    // A separate array for preview rects to allow real-time updates without affecting capture
    cellPreviewRects: [],
    verticalLines: [],
    horizontalLines: [],
    draggingLine: { type: null, index: -1 },
};